export default {
  sport: [
    {
      game_platform_id: 13,
      game_cate_id: 4,
      id: 'IBC',
      url: '/src/assets/images/games/sport/IBC.png',
      name: 'IBC体育',
    },
    {
      game_platform_id: 136,
      game_cate_id: 4,
      id: 'BTI',
      url: '/src/assets/images/games/sport/BTI.png',
      name: 'BTI体育',
    },
    {
      game_platform_id: 117,
      game_cate_id: 4,
      id: 'IM',
      url: '/src/assets/images/games/sport/IM.png',
      name: 'IM体育',
    },
  ],
  esport: [
    {
      game_platform_id: 13,
      game_cate_id: 8,
      id: 'IBC',
      url: '/src/assets/images/games/esport/IBC.png',
      name: 'IBC电竞',
    },
    // {
    //   game_platform_id: 136,
    //   game_cate_id: 8,
    //   id: 'BTI',
    //   url: '/src/assets/images/games/esport/BTI.png',
    //   name: 'BTI电竞',
    // },
    {
      game_platform_id: 118,
      game_cate_id: 8,
      id: 'IM',
      url: '/src/assets/images/games/esport/IM.png',
      name: 'IM电竞',
    },
  ],
  electron: [
    {
      game_platform_id: 7,
      game_cate_id: 2,
      id: 'MG',
      url: '/src/assets/images/games/electron/MG.png',
      name: 'MG平台',
    },
    {
      game_platform_id: 2,
      game_cate_id: 2,
      id: 'PT',
      url: '/src/assets/images/games/electron/PT.png',
      name: 'PT平台',
    },
    {
      game_platform_id: 107,
      game_cate_id: 2,
      id: 'PP',
      url: '/src/assets/images/games/electron/PP.png',
      name: 'PP平台',
    },
    {
      // game_platform_id: 107,
      game_cate_id: 2,
      game_platform_id: 134,
      id: 'PG',
      url: '/src/assets/images/games/electron/PG.png',
      name: 'PG平台',
    },
    {
      game_platform_id: 3,
      id: 'BBIN',
      url: '/src/assets/images/games/electron/BBIN.png',
      name: 'BBIN平台',
    },
    // {
    //   id: 'more',
    //   url: '/src/assets/images/games/electron/more.png',
    //   name: 'more',
    // },
  ],
  real: [
    {
      game_platform_id: 1,
      game_cate_id: 1,
      id: 'AG',
      url: '/src/assets/images/games/real/AG.png',
      name: 'AG平台',
    },
    {
      game_platform_id: 140,
      game_cate_id: 1,
      id: 'N2Live',
      url: '/src/assets/images/games/real/N2Live.png',
      name: 'N2Live平台',
    },
    {
      game_platform_id: 138,
      game_cate_id: 1,
      id: 'SEXY',
      url: '/src/assets/images/games/real/SEXY.png',
      name: 'SEXY平台',
    },
    // {
    //   id: 'GAMING',
    //   url: '/src/assets/images/games/real/GAMING.png',
    //   name: 'GAMING平台',
    // },
    {
      game_platform_id: 139,
      game_cate_id: 1,
      id: 'GDG',
      url: '/src/assets/images/games/real/GD.png',
      name: 'GDG平台',
    },
    {
      game_platform_id: 137,
      game_cate_id: 1,
      id: 'SA',
      url: '/src/assets/images/games/real/SA.png',
      name: 'SA平台',
    },
  ],
  lottery: [
    {
      // default_game_id: 4393,
      game_platform_id: 141,
      game_cate_id: 5,
      id: 'VR',
      url: '/src/assets/images/games/lottery/vr_gf.png',
      name: 'GPI平台',
    },
    // {
    //   default_game_id: 4400,
    //   game_platform_id: 121,
    //   id: 'VR',
    //   url: '/src/assets/images/games/lottery/VR.png',
    //   name: 'VR彩票-六合彩',
    // },
    // {
    //   default_game_id: 4379,
    //   game_platform_id: 121,
    //   id: 'VR',
    //   url: '/src/assets/images/games/lottery/vr_vr.png',
    //   name: 'VR彩票-VR彩',
    // },
    // {
    //   default_game_id: 4421,
    //   game_platform_id: 122,
    //   id: 'SG-Win',
    //   url: '/src/assets/images/games/lottery/SG.png',
    //   name: 'SG-Win 双赢彩票',
    // },
    // {
    //   default_game_id: 4338,
    //   game_platform_id: 120,
    //   id: 'IG',
    //   url: '/src/assets/images/games/lottery/IG.png',
    //   name: 'IG彩票',
    // },
  ],
  // fish: [
  //   {
  //     game_platform_id: 1,
  //     game_cate_id: 3,
  //     id: 'AG',
  //     url: '/src/assets/images/games/fish/AG.png',
  //     name: 'AG捕鱼',
  //   },
  //   // {
  //   //   id: 'SEXY',
  //   //   game_cate_id: 3,
  //   //   url: '/src/assets/images/games/fish/SEXY.png',
  //   //   name: 'PP捕鱼',
  //   // },
  //   // {
  //   //   id: 'SA',
  //   //   url: '/src/assets/images/games/fish/SA.png',
  //   //   name: 'SA捕鱼',
  //   // },
  // ],
};

// export default {
//   sport: {
//     id: 4,
//     list: [
//       {
//         game_platform_id: 13,
//         game_cate_id: 4,
//         id: 'IBC',
//         url: '/src/assets/images/games/sport/IBC.png',
//         name: 'IBC体育',
//       },
//       {
//         game_platform_id: 136,
//         game_cate_id: 4,
//         id: 'BTI',
//         url: '/src/assets/images/games/sport/BTI.png',
//         name: 'BTI体育',
//       },
//       {
//         game_platform_id: 117,
//         game_cate_id: 4,
//         id: 'IM',
//         url: '/src/assets/images/games/sport/IM.png',
//         name: 'IM体育',
//       },
//     ],
//   },
//   esport: {
//     id: 8,
//     list: [
//       {
//         game_platform_id: 13,
//         game_cate_id: 8,
//         id: 'IBC',
//         url: '/src/assets/images/games/esport/IBC.png',
//         name: 'IBC电竞',
//       },
//       // {
//       //   game_platform_id: 136,
//       //   game_cate_id: 8,
//       //   id: 'BTI',
//       //   url: '/src/assets/images/games/esport/BTI.png',
//       //   name: 'BTI电竞',
//       // },
//       {
//         game_platform_id: 118,
//         game_cate_id: 8,
//         id: 'IM',
//         url: '/src/assets/images/games/esport/IM.png',
//         name: 'IM电竞',
//       },
//     ],
//   },
//   electron: {
//     id: 2,
//     list: [
//       {
//         game_platform_id: 7,
//         game_cate_id: 2,
//         id: 'MG',
//         url: '/src/assets/images/games/electron/MG.png',
//         name: 'MG平台',
//       },
//       {
//         game_platform_id: 2,
//         game_cate_id: 2,
//         id: 'PT',
//         url: '/src/assets/images/games/electron/PT.png',
//         name: 'PT平台',
//       },
//       {
//         game_platform_id: 107,
//         game_cate_id: 2,
//         id: 'PP',
//         url: '/src/assets/images/games/electron/PP.png',
//         name: 'PP平台',
//       },
//       {
//         // game_platform_id: 107,
//         game_cate_id: 2,
//         game_platform_id: 134,
//         id: 'PG',
//         url: '/src/assets/images/games/electron/PG.png',
//         name: 'PG平台',
//       },
//       {
//         game_platform_id: 3,
//         id: 'BBIN',
//         url: '/src/assets/images/games/electron/BBIN.png',
//         name: 'BBIN平台',
//       },
//       // {
//       //   id: 'more',
//       //   url: '/src/assets/images/games/electron/more.png',
//       //   name: 'more',
//       // },
//     ],
//   },
//   real: {
//     id: 2,
//     list: [
//       {
//         game_platform_id: 1,
//         game_cate_id: 1,
//         id: 'AG',
//         url: '/src/assets/images/games/real/AG.png',
//         name: 'AG平台',
//       },
//       {
//         game_platform_id: 140,
//         game_cate_id: 1,
//         id: 'N2Live',
//         url: '/src/assets/images/games/real/N2Live.png',
//         name: 'N2Live平台',
//       },
//       {
//         game_platform_id: 138,
//         game_cate_id: 1,
//         id: 'SEXY',
//         url: '/src/assets/images/games/real/SEXY.png',
//         name: 'SEXY平台',
//       },
//       // {
//       //   id: 'GAMING',
//       //   url: '/src/assets/images/games/real/GAMING.png',
//       //   name: 'GAMING平台',
//       // },
//       {
//         game_platform_id: 139,
//         game_cate_id: 1,
//         id: 'GDG',
//         url: '/src/assets/images/games/real/GD.png',
//         name: 'GDG平台',
//       },
//       {
//         game_platform_id: 137,
//         game_cate_id: 1,
//         id: 'SA',
//         url: '/src/assets/images/games/real/SA.png',
//         name: 'SA平台',
//       },
//     ],
//   },
//   lottery: {
//     id: 5,
//     list: [
//       {
//         // default_game_id: 4393,
//         game_platform_id: 141,
//         game_cate_id: 5,
//         id: 'VR',
//         url: '/src/assets/images/games/lottery/vr_gf.png',
//         name: 'GPI平台',
//       },
//       // {
//       //   default_game_id: 4400,
//       //   game_platform_id: 121,
//       //   id: 'VR',
//       //   url: '/src/assets/images/games/lottery/VR.png',
//       //   name: 'VR彩票-六合彩',
//       // },
//       // {
//       //   default_game_id: 4379,
//       //   game_platform_id: 121,
//       //   id: 'VR',
//       //   url: '/src/assets/images/games/lottery/vr_vr.png',
//       //   name: 'VR彩票-VR彩',
//       // },
//       // {
//       //   default_game_id: 4421,
//       //   game_platform_id: 122,
//       //   id: 'SG-Win',
//       //   url: '/src/assets/images/games/lottery/SG.png',
//       //   name: 'SG-Win 双赢彩票',
//       // },
//       // {
//       //   default_game_id: 4338,
//       //   game_platform_id: 120,
//       //   id: 'IG',
//       //   url: '/src/assets/images/games/lottery/IG.png',
//       //   name: 'IG彩票',
//       // },
//     ],
//   },
//   fish: {
//     id: 3,
//     list: [
//       {
//         game_platform_id: 1,
//         game_cate_id: 3,
//         id: 'AG',
//         url: '/src/assets/images/games/fish/AG.png',
//         name: 'AG捕鱼',
//       },
//       {
//         id: 'SEXY',
//         game_cate_id: 3,
//         url: '/src/assets/images/games/fish/SEXY.png',
//         name: 'PP捕鱼',
//       },
//       // {
//       //   id: 'SA',
//       //   url: '/src/assets/images/games/fish/SA.png',
//       //   name: 'SA捕鱼',
//       // },
//     ],
//   },
// };
